### ISSUE TITLE
عدم دریافت نوتیف  هنگام بسته بودن برنامه

### ISSUE THREAD

**Issue by mohamadyamini4** [chabokpush/chabok-starter-android#4]
سلام من کد هایی که باید رو  پیاده کردم قسمت عیب یابی هم خوندم متاسفانه هنگامی که ا\لیکیشن از تسک منیجر بسته باشه نوتیف دریافت نمیشه

**Comment by Husseinhj** [comment]
<p dir="rtl">با اپ استارت روی حساب کاربری پنل خودتون هم تست کردید؟</p>
<p dir="rtl">پروژه استارتر رو با اطلاعات حساب خودتون همراه با senderId اکانت خودتون امتحان کنید.</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">من ایشو رو میبندم چون مشکل شما علت استفاده از کتابخانه‌ای بوده که اجازه نمایش پوش‌نوتیفیکیشن رو نمیداد و مشکل شما حل شده</p>
