### ISSUE TITLE
عدم دریافت پوش‌نوتیفیکیشن به هنگام بسته بودن اپلیکیشن

### ISSUE THREAD

**Issue by mahdi302** [chabokpush/chabok-starter-android#5]
سلام..من تمام مراحل راه اندازی واسه قسنت اندروید رو انجام دادم ولی فقط زمانی ک برنامه باز هستش کار میکنه و وقتی برنامه بسته هستش نوتیفکیشن واسم نمیاد..میشه دلیلشو بگین

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">وقتی برنامه بسته هستش نوتیفکیشن واسم نمیاد</p>
</blockquote>
<p dir="rtl">لطفا بخش <a href="https://doc.chabokpush.com/android/troubleshoot.html">عیب‌یابی</a> را مطالعه بفرمایید.
لطفا روی پروژه استارتر در همین ریپازتوری بخش‌ها را مطالعه بفرمایید
</p>

**Comment by mahdi302** [comment]
هم قسمت عیب یابی هم پروژه استارتر رو نگاه کردم..همه چیزا ظاهرا درسته و بازم موقعی که برنامه تو بک گرانده میتونم پیام ارسال کنم

**Comment by mahdi302** [comment]
واسه فرستادن پیام حتما باید کانال تعریف کنی..؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">هم قسمت عیب یابی هم پروژه استارتر رو نگاه کردم..همه چیزا ظاهرا درسته و بازم موقعی که برنامه تو بک گرانده میتونم پیام ارسال کنم</p>
</blockquote>
<p dir="rtl">آیا با پروژه استارتر بدون هیچ تغییر کدی زمانی که کد را اجرا می‌کنید در حالتی که اپلیکیشن بسته است باز هم اعلان دریافت نمی‌کنید؟
مدل دستگاه شما و نسخه اندروید شما چیست؟</p>
<p dir="rtl">اطلاعات پوش‌نوتیفیکیشن را در تنظیمات اندروید در پنل به درستی اعمال کرده‌اید؟</p>
<blockquote dir="rtl">
<p dir="rtl">واسه فرستادن پیام حتما باید کانال تعریف کنی..؟</p>
</blockquote>
<p dir="rtl">خیر اگر مقدار کانال را وارد نکنید چابک به صورت پیش‌فرض به کانال  پیش‌فرض (default)خصوصی آن کاربر (userId) پیام ارسال می‌کند. </p>

**Comment by mahdi302** [comment]
اول اینکه چجوری باید واسه پروژه استارتر پوش بفرستم..
مدل دستگاه من ایسوز هستش..در مورد اطلاعات پوش نوتیفیکیشن باید بگم ک از اطلاعاتی ک قبلا واسه ی پوش دیگ استفاده میکردم واسه همینم استفاده میکنم

**Comment by mahdi302** [comment]
بجز اضافه کردن دیپندنسی تو قسمت گردل باید فایل های آی آی آر هم ب پروژه اضافه بشن..؟

**Comment by mahdi302** [comment]
مشکلم حل شد..مرسی از راهنماییاتون..دلیلشم این بود ک من از سرویس پوشه هم توی برنامه ام استفاده میکردم و همین قضیه باعث میشد ک من نتونم توی سرویس چابک وقتی برنامه بسته هستش پوش بگیرم

**Comment by mahdi302** [comment]
واسه استفاده از سرویس چابک دیگ نباید از سرویس پوشه استفاده کنید
