### ISSUE TITLE
does chabok support FCM?

### ISSUE THREAD

**Issue by ImanX** [chabokpush/chabok-starter-android#6]
I did read your android integrate document and What surprised me it was you are supporting GCM, does chabok support FCM? GCM service is deprecating.

**Comment by Husseinhj** [comment]
This issue has already been addressed. Please check issue [#17](https://github.com/chabokpush/chabok-panel/issues/17).

**Comment by behrad** [comment]
Chabok uses FCM in server side to connect to Google Cloud, however for sake of our user's compatibility we have postponed to support FCM in our client SDK however Chabok SDK will deprecate GCM and move to client side FCM configuration soon.
