### ISSUE TITLE
com.google.android.gms.gcm.GcmReceiver is deprecated

### ISSUE THREAD

**Issue by arefhosseini** [chabokpush/chabok-starter-android#7]
as [Google](https://developers.google.com/cloud-messaging/android/android-migrate-fcm) said :
**On April 10, 2018, Google deprecated GCM. The GCM server and client APIs were removed on May 29, 2019**
Is migrating GCM to FCM affect Chabok push notification or not? 
Thanks.

**Comment by behrad** [comment]
Chabok Client SDK currently supports GcmReceiver for backward compatibility of our Customers with old dependencies, however FCM is already supported & used by Chabok server API.
This won't affect push notifications using Chabok SDK :)
